name: 🚀 Deploy website on push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --frozen-lockfile

      - name: yarn build
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -az
          path: dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
