name: 🚀 Deploy website on push

on:
  push:
    branches:
      - rsync-github-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: yarn build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -az
          path: dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
